language: python
sudo: false
cache:
  - pip
python:
  - "3.6"
  - "3.5"
  - "nightly"
install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements-dev.txt
  - pip install --upgrade -r requirements.txt
  - pip freeze
  - pip install --upgrade -e .[test]
script:
  - pytest -v --maxfail=2 bookstore/tests
after_success:
  - codecov
